package server;

public enum ReponseEnum {
	ERREUR_FIN_REQUETE,
	SYNTAXE_APOGEE,
	NOM_EXISTE_DEJA,
	SYNTAXE_QUALITE,
	DEPARTEMENT_INCONNU,
	NOM_INCONNU,
	SURNOM_INCONNU,
	FILTRE_INCONNU,
	SERVICE_INCONNU,
	SUC
}
