package server;

public enum ReponseEnum {
	ERREUR_FIN_REQUETE("ERREUR_FIN_REQUETE"),
	SYNTAXE_APOGEE("SYNTAXE_APOGEE"),
	NOM_EXISTE_DEJA("NOM_EXISTE_DEJA"),
	SYNTAXE_QUALITE("SYNTAXE_QUALITE"),
	DEPARTEMENT_INCONNU("DEPARTEMENT_INCONNU"),
	NOM_INCONNU("NOM_INCONNU"),
	SURNOM_INCONNU("SURNOM_INCONNU"),
	FILTRE_INCONNU("FILTRE_INCONNU"),
	SERVICE_INCONNU("SERVICE_INCONNU"),
	SUC("SUC");
	
	private String nom = "";
	private ReponseEnum(String nom){
		this.nom=nom;
	}
	public String toString(){
		return ""+nom;
	}
}
