package client;
public enum ServiceN {
	AJOUTER_NOM,
	AJOUTER_SURNOM,
	SUPPRIMER_SURNOM,
	SUPPRIMER_NOM,
	LISTER_UN,
	LISTER_REQUETE,
	LISTER_TOUT,
	MODIFIER_NOM,
	MODIFIER_SURNOM,
	MODIFIER_APOGEE,
	MODIFIER_QUALITE,
	MODIFIER_DEPARTEMENT;
}
