package client;
public enum ServiceN {
	REQ("REQ"),
	DECONNECTION("DECONNECTION"),
	AJOUTER_NOM("AJOUTER_NOM"),
	AJOUTER_SURNOM("AJOUTER_SURNOM"),
	SUPPRIMER_SURNOM("SUPPRIMER_SURNOM"),
	SUPPRIMER_NOM("SUPPRIMER_NOM"),
	LISTER_UN("LISTER_UN"),
	LISTER_REQUETE("LISTER_REQUETE"),
	LISTER_TOUT("LISTER_TOUT"),
	MODIFIER_NOM("MODIFIER_NOM"),
	MODIFIER_SURNOM("MODIFIER_SURNOM"),
	MODIFIER_APOGEE("MODIFIER_APOGEE"),
	MODIFIER_QUALITE("MODIFIER_QUALITE"),
	MODIFIER_DEPARTEMENT("MODIFIER_DEPARTEMENT");
	
	private String name;
	
	private ServiceN(String s){
		this.name = s;
	}
	
	public String toString(){
		return name;
	}
}
